version: '3'

services:
  hugo-server:
    image: klakegg/hugo:0.101.0
    restart: unless-stopped
    container_name: hugo-server
    command: server
    volumes:
      - ".:/src"
      
networks:
  default:
    name: ubuntu_default
    external: true
